# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'TrackApp' do
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Database'

end

target 'TrackAppTests' do

end

target 'TrackAppUITests' do

end

